services:
  - type: web
    name: journal-app
    env: java
    plan: free
    buildCommand: ./mvnw clean package
    startCommand: java -Dserver.port=$PORT -jar target/JournalWithoutDB-0.0.1-SNAPSHOT.jar
